name:
channels:
  - conda-forge
  - defaults
dependencies:
  - biopython=1.81
  - cctbx=2022.5
  - cctbx-base=2022.5
  - keras=2.11.0
  - keras-preprocessing=1.1.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mrcfile=1.4.3
  - pymol-open-source=2.5.0
  - python=3.10.12
  - scipy=1.11.1
  - tensorflow=2.11.0
  - tensorflow-base=2.11.0
  - pip:
      - anyio==4.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - async-lru==2.0.4
      - babel==2.12.1
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - comm==0.1.4
      - configparser==6.0.0
      - debugpy==1.8.0
      - defusedxml==0.7.1
      - docutils==0.20.1
      - exceptiongroup==1.1.3
      - fastjsonschema==2.18.0
      - flit==3.9.0
      - flit-core==3.9.0
      - fqdn==1.5.1
      - gemmi==0.6.4
      - imageio==2.33.1
      - ipykernel==6.25.2
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jinja2==3.1.2
      - joblib==1.3.1
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-client==8.3.1
      - jupyter-console==6.6.3
      - jupyter-core==5.3.1
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.3
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.6
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.0
      - jupyterlab-widgets==3.0.9
      - kneed==0.8.5
      - mistune==3.0.1
      - mpmath==1.3.0
      - nbclient==0.8.0
      - nbconvert==7.8.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.1
      - notebook==7.0.4
      - notebook-shim==0.2.3
      - numpy==1.21.6
      - opencv-python==4.8.0.74
      - overrides==7.4.0
      - pandas==1.3.5
      - pandocfilters==1.5.0
      - prometheus-client==0.17.1
      - python-json-logger==2.0.7
      - pytz==2023.3
      - pyyaml==6.0.1
      - qtconsole==5.4.4
      - qtpy==2.4.0
      - referencing==0.30.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.10.3
      - ruptures==1.1.9
      - scikit-learn==1.3.0
      - seaborn==0.12.2
      - send2trash==1.8.2
      - sniffio==1.3.0
      - soupsieve==2.5
      - sympy==1.12
      - terminado==0.17.1
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - tomli-w==1.0.0
      - tornado==6.3.3
      - tqdm==4.65.0
      - tzdata==2023.3
      - uri-template==1.3.0
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.3
      - widgetsnbextension==4.0.9
