name: Auto-Merge Doc Security PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
  # Add manual trigger option
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number to auto-merge'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    # Different conditions based on trigger type
    if: |
      (github.event_name == 'pull_request' && 
       contains(github.event.pull_request.labels.*.name, 'documentation') &&
       contains(github.event.pull_request.labels.*.name, 'security') &&
       contains(github.event.pull_request.labels.*.name, 'dependencies') &&
       contains(github.event.pull_request.labels.*.name, 'automated-pr')) ||
      github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # For workflow_dispatch, checkout the PR branch
          ref: ${{ github.event_name == 'workflow_dispatch' && format('refs/pull/{0}/head', github.event.inputs.pr_number) || github.ref }}
      
      - name: Set up Python 3.12.5
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.5"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e ".[docs]"
      
      - name: Test documentation build
        run: |
          cd docs
          make html
      
      # Two separate steps for different event types
      - name: Auto-merge PR event
        if: github.event_name == 'pull_request' && success()
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --auto --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Auto-merge manual
        if: github.event_name == 'workflow_dispatch' && success()
        run: |
          gh pr merge ${{ github.event.inputs.pr_number }} --squash --auto --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
