name: Manual Security Fix

on:
  workflow_dispatch:
    inputs:
      fix_all_current:
        description: 'Fix all current security alerts'
        required: false
        default: true
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  create-fix:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.12.5
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.5"
      
      - name: Create branch for changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b fix-security-vulnerabilities-$(date +%Y%m%d)
      
      - name: Update vulnerable packages
        run: |
          # Create or update requirements.txt
          touch requirements.txt
          
          # Update all current vulnerable packages
          echo "Updating setuptools to secure version"
          if grep -q "setuptools" requirements.txt; then
            sed -i 's/setuptools[<>=]*[0-9\.]*/setuptools>=68.0.0/' requirements.txt
          else
            echo "setuptools>=68.0.0" >> requirements.txt
          fi
          
          echo "Updating tornado to secure version"
          if grep -q "tornado" requirements.txt; then
            sed -i 's/tornado[<>=]*[0-9\.]*/tornado>=6.3.2/' requirements.txt
          else
            echo "tornado>=6.3.2" >> requirements.txt
          fi
          
          echo "Updating jinja2 to secure version"
          if grep -q "jinja2" requirements.txt; then
            sed -i 's/jinja2[<>=]*[0-9\.]*/jinja2>=3.1.2/' requirements.txt
          else
            echo "jinja2>=3.1.2" >> requirements.txt
          fi
          
          echo "Updating certifi to secure version"
          if grep -q "certifi" requirements.txt; then
            sed -i 's/certifi[<>=]*[0-9\.]*/certifi>=2023.7.22/' requirements.txt
          else
            echo "certifi>=2023.7.22" >> requirements.txt
          fi
          
          # Also update in docs/requirements.txt if it exists
          if [ -f "docs/requirements.txt" ]; then
            if grep -q "setuptools" docs/requirements.txt; then
              sed -i 's/setuptools[<>=]*[0-9\.]*/setuptools>=68.0.0/' docs/requirements.txt
            else
              echo "setuptools>=68.0.0" >> docs/requirements.txt
            fi
            
            if grep -q "tornado" docs/requirements.txt; then
              sed -i 's/tornado[<>=]*[0-9\.]*/tornado>=6.3.2/' docs/requirements.txt
            else
              echo "tornado>=6.3.2" >> docs/requirements.txt
            fi
            
            if grep -q "jinja2" docs/requirements.txt; then
              sed -i 's/jinja2[<>=]*[0-9\.]*/jinja2>=3.1.2/' docs/requirements.txt
            else
              echo "jinja2>=3.1.2" >> docs/requirements.txt
            fi
            
            if grep -q "certifi" docs/requirements.txt; then
              sed -i 's/certifi[<>=]*[0-9\.]*/certifi>=2023.7.22/' docs/requirements.txt
            else
              echo "certifi>=2023.7.22" >> docs/requirements.txt
            fi
          fi
      
      - name: Test documentation build
        id: test_build
        continue-on-error: true
        run: |
          pip install -r requirements.txt
          pip install -e ".[docs]"
          cd docs
          make html
          
          if [ $? -eq 0 ]; then
            echo "BUILD_SUCCESS=true" >> $GITHUB_OUTPUT
          else
            echo "BUILD_SUCCESS=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.test_build.outputs.BUILD_SUCCESS == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "security: Update vulnerable dependencies [skip docs]"
          title: "Security: Update vulnerable dependencies"
          body: |
            # Security Update
            
            This PR updates multiple packages to fix security vulnerabilities currently flagged by Dependabot.
            
            ## Updates:
            - setuptools to >=68.0.0
            - tornado to >=6.3.2
            - jinja2 to >=3.1.2
            - certifi to >=2023.7.22
            
            The documentation builds successfully with these updates.
            
            This PR was created by the Manual Security Fix workflow.
          branch: fix-security-vulnerabilities-$(date +%Y%m%d)
          labels: security,documentation,dependencies,automated-pr
          delete-branch: true
      
      - name: Report build failure
        if: steps.test_build.outputs.BUILD_SUCCESS != 'true'
        run: |
          echo "::error::Documentation build failed with the updated dependencies. Please check compatibility."
